CREATE TABLE `user` (
	`uid` INT UNSIGNED AUTO_INCREMENT,
	`uname` VARCHAR(255) NOT NULL UNIQUE,
	`passwd` VARCHAR(50) NOT NULL,
	`phone` CHAR(11) NOT NULL,
	`email` varchar(255) NOT NULL,
	PRIMARY KEY (`uid`)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8 